### ISSUE TITLE
3 Layer IK makes all structures the same length, Unusable for custom artwork

### ISSUE THREAD

**Issue by pikero24** [RxLaboratory/DuAEF_Duik#720]
**Describe the bug**
When I use 3 Layer rigging, all of the structures become the same length and no longer line up with my artwork

I'm rigging a finger. I'm making a custom 3 layer structure and then rigging using IK> 3 Layer Rigging.

**To Reproduce**
1. Create Custom Structure with 3 elements.
2. Rearrange the structure bones
3. Auto-rig options > IK > 3 Layer IK
4. The size of the structures all become the same and do not line up with the artwork anymore, making it impossible to rig properly. 

**Expected behavior**
I'd expect the structures to stay the same as before activating IK

Screenshots:
Before Rigging:
https://i.imgur.com/QOmErqr.png
After Rigging:
https://i.imgur.com/RgEVT1P.png

**System (please complete the following information):**
 - OS: Windows 10
 - Version of After Effects: 17.1.2
 - Version of Duik: 16.2.16 (the most recent from the website as of today)

**Comment by Nico-Duduf** [comment]
Hi,

Unfortunately, that's a current limitation of the 3-layer IK, which is quite complex to workaround in After Effects.
I should explain that in the FAQ actually.

When rigging a limb with 2 joints, it's better to use a combination of one-layer and two-layer IK. You'd have more control while still having something quite automated; that's how crabs, insects and stuff like that are usually rigged in 3D software too, just because with an IK for many joints, the animator does not have enough control over the limb

**Comment by Nico-Duduf** [comment]
this combination of one-layer and two-layer is what Duik uses for an arm with a shoulder actually, you can create one to see how it works

**Comment by pikero24** [comment]
Yeah I checked the docs/FAQ and didn't find anything which is why I filed the bug.

I found a workaround however. When I apply the 3 layer IK to the art layers directly instead of the structures the rigging works fine. Figured I'd let you know. 

Thanks for making DUIK what it is! I appreciate it!

**Comment by Nico-Duduf** [comment]
Hum funny, I don't know why this workaround actually works, I'll have a look at that. Maybe there's an easy way to make it work with structures!
