### ISSUE TITLE
IK rigging with duik bassel 2 

### ISSUE THREAD

**Issue by somy1420** [RxLaboratory/DuAEF_Duik#816]
**Describe the bug**
I'm new to rigging, I have used the " duik " after effects plugin a couple of times and haven't no problem, until today that I wanted to rig an arm, I positioned anchor points at the right position for "Finger" , " Hand" , "Lower_Arm" and "Upper_Arm" layers, then select the "Hand" layer and create a controller, and then select the "Hand" , "Lower_Arm", "Upper_Arm" layers and then the controller and then hit the " IK " button on duik plugin, every time I was doing this process before , it worked but not this time! it crashes and the layers go in different position and rotation, by the way I'm in standered mode on duik, I changed the mode to "Expert" and also experiment different IK modes(2 layer ik , 3 layer ik) to see if that resolves the problem but that didn't happen. Please help! 
 

![1](https://user-images.githubusercontent.com/79407734/108627793-99c44980-746c-11eb-919e-d737ae0d4afc.png)
![2](https://user-images.githubusercontent.com/79407734/108627813-afd20a00-746c-11eb-88d5-6ccbbd8f4a4d.png)
![3](https://user-images.githubusercontent.com/79407734/108627849-da23c780-746c-11eb-8d86-82b97a832ef3.png)

**System**
 - OS: windows 10
 - Version of After Effects: 2019 (16.1.3)
 - Version of Duik: 16.2.28

**Comment by Nico-Duduf** [comment]
Sorry to reply so late,

The layers look like they've been stretched, aren't they?
IK need all the scales to be the same in X and Y (and preferably 100%).

If that's the case, you could use structures instead of adding the IK directly on the layers.
If not, that's a bug and if you could send me your project file so I can have a look that'd be great ;)

Thanks
